import tkinter
win=tkinter.Tk()
win.title('synnefo')
win.geometry=('400x400')
win.maxsize(600,600)
win.minsize(100,100)
win.config(background='green')
def data():
    l4=tkinter.Label(win)
    l4.pack()
    data=e1.get()
    data1=v1.get()
    l4.config(text=data)
    print(data1)
l1=tkinter.Label(win,text='welcome')
l2=tkinter.Label(win,text='to' )
l3=tkinter.Label(win,text='all')
l1.pack()
# l1.place(x=20,y=30)
# l1.grid(row=0,column=0)
# l2.grid(row=0,column=2)
# l3.grid(row=0,column=3)
e1=tkinter.Entry(win,background='white',foreground='black')
e1.pack()
b1=tkinter.Button(win,background='blue',foreground='white',text='send',padx=5,pady=5,command=data)
b1.pack()
v1=tkinter.IntVar()
c1=tkinter.Checkbutton(win,variable=v1,text='sslc')
c1.pack()
win.mainloop() 